version: '3.3'

services:
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "127.0.0.1:27017:27017"
    command: mongod --quiet --logpath /dev/null

  # redis:
  #   image: redis:6.2
  #   command: redis-server --requirepass redis
  #   ports:
  #     - "127.0.0.1:6379:6379"
